/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zbook;

import java.awt.Cursor;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Zack
 */
public class SearchPatronPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPatronPanel
     */
    public SearchPatronPanel(String first, String last, int id, String status,int fines) {
        initComponents();
        firstNameLabel.setText("First: "+first);
        lastNameLabel.setText("Last: "+last);
        patronIDLabel.setText("Patron ID: "+id);
        statusLabel.setText("Status: "+status);
        finesLabel.setText("Fines: $"+fines);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        patronIDLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        finesLabel = new javax.swing.JLabel();
        createBookingButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        viewPatronLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(310, 127));
        setMinimumSize(new java.awt.Dimension(310, 127));

        firstNameLabel.setText("First: ");

        lastNameLabel.setText("Last:");

        patronIDLabel.setText("Patron ID: ");

        statusLabel.setText("Status: ");

        finesLabel.setText("Fines: ");

        createBookingButton.setText("create booking");
        createBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBookingButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        viewPatronLabel.setForeground(java.awt.Color.blue);
        viewPatronLabel.setText("view patron");
        viewPatronLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPatronLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPatronLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPatronLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(finesLabel)
                            .addComponent(patronIDLabel))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(createBookingButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewPatronLabel)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patronIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finesLabel)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewPatronLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createBookingButton)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewPatronLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPatronLabelMouseEntered
        viewPatronLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_viewPatronLabelMouseEntered

    private void viewPatronLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPatronLabelMouseExited
        viewPatronLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_viewPatronLabelMouseExited

    private void viewPatronLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPatronLabelMouseClicked
        DefaultListModel model = new DefaultListModel();
        MainUI.itemsList.setModel(model);
        model.removeAllElements();
        
        MainUI.firstNameLabel.setText(firstNameLabel.getText());
        MainUI.lastNameLabel.setText(lastNameLabel.getText());
        MainUI.patronIDLabel.setText(patronIDLabel.getText());
        MainUI.statusLabel.setText(statusLabel.getText());
        MainUI.finesLabel.setText(finesLabel.getText());
        
        Connection c = new DBConnector().connect();
        
        try {

                String query = "select name, copy_number, status from HAS NATURAL JOIN ITEM where patron_ID == "+patronIDLabel.getText().substring(11);
                String sizeQuery = "select count(*) as size from (" + query + ");";
                query += " ORDER BY start_time, copy_number;";

                Statement stmt = c.createStatement();

                ResultSet rs = stmt.executeQuery(sizeQuery);
                int size = rs.getInt("size");

                if (size == 0) {
                    //System.out.println("size is 0 -- leaving method");
                    c.close();
                    //JOptionPane.showMessageDialog(null, "No search results found for \"" + search + "\"", "0 search results found", JOptionPane.INFORMATION_MESSAGE)
                    return;
                }

                //System.out.println("Just Executed size Query, we have X rows: "+size);
                rs = stmt.executeQuery(query);

                for (int i = 0; i < size; i++) {
                    rs.next();
                    //System.out.println("ITEM NUMBER "+"i"+" ############################# "+ i);
                    String name = rs.getString("name");
                    //System.out.println("name: "+name);

                    int copyNumber = rs.getInt("copy_number");
                   
                    model.addElement(name+"  -  copy no. "+copyNumber);
                }

                c.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getClass().getName() + ": " + e.getMessage());
            }
    }//GEN-LAST:event_viewPatronLabelMouseClicked

    private void createBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingButtonActionPerformed
        CreateBookingUI.runCreateBookingUI(firstNameLabel.getText(),lastNameLabel.getText(),patronIDLabel.getText());
    }//GEN-LAST:event_createBookingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBookingButton;
    private javax.swing.JLabel finesLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel patronIDLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel viewPatronLabel;
    // End of variables declaration//GEN-END:variables
}
